services:
  esl-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - SIP_ENDPOINT=username@linhome.org
  freeswitch:
    build:
      context: ./freeswitch
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: "host"
    environment:
      - EXTENSION_PASSWORD=extensionpassword
